In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from bokeh.plotting import figure, output_file, show
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
from bokeh.plotting import figure, show, output_file, output_notebook
from bokeh.palettes import Spectral11, colorblind, Inferno, BuGn, brewer
from bokeh.models import HoverTool, value, LabelSet, Legend, ColumnDataSource,LinearColorMapper,BasicTicker, PrintfTickFormatter, ColorBar
import datetime
import os

In [2]:
data = pd.read_csv("DataTable201.csv", parse_dates=['Time'])
# data.head()

In [3]:
# data.Time.min(), data.Time.max()

In [4]:
# data.PMin.value_counts()

In [5]:
# data['Year'] = data.Time.apply(lambda x: x.year)
# data['Month'] = data.Time.apply(lambda x: x.month)
# data['Day'] = data.Time.apply(lambda x: x.day)
# data['Hour'] = data.Time.apply(lambda x: x.hour)
# data['Minute'] = data.Time.apply(lambda x: x.minute)
# data['Second'] = data.Time.apply(lambda x: x.second)
# data.head()

In [6]:
# temp_df = data.groupby(['Day']).sum().reset_index()
# temp_df

In [7]:
# time = temp_df["Day"].values
# pmin = temp_df["PMin"].values
# print(time)
# print(pmin)

# # output to static HTML file
# output_file("pmin.html")

# # create a new plot with a title and axis labels
# plo = figure(title="pmin", x_axis_label='time', y_axis_label='pmin')

# # add a line renderer with legend and line thickness
# plo.line(time, pmin, legend="Temp.", line_width=2)

# # show the results
# show(plo)

In [8]:
df = data = pd.read_csv("DataTable201.csv", parse_dates=['Time'])
df['Time'] = pd.to_datetime(df['Time'], format='%m/%d/%Y%H%M')
df

,Time,PMin,PMout,AVP_BR1_PM25,AVP_BR1_PM10,AVP_BR1_CO2,AVP_BR1_T,AVP_BR1_RH,AVP_IN1_PM25,AVP_IN1_PM10,...,ANM_RHD,MTR_CDR,STA_BR1,STA_DFR,STA_DP1,IBU_CLB,IBU_CLF,IBU_CRB,IBU_CRF,IBU_OVN
0,2018-07-24 18:00:00,1,3.0,0.000000,0.000000,915.000000,25.45,57.0,0.000000,0.000000,...,0.0,0,0,100,100,27.5,28.5,27.0,27.5,27.5
1,2018-07-24 18:01:00,1,3.0,0.000000,0.000000,914.000000,25.45,57.0,0.000000,0.000000,...,0.0,0,0,100,100,27.5,28.5,27.0,27.5,27.5
2,2018-07-24 18:02:00,1,2.0,0.000000,0.000000,913.333333,25.50,57.0,0.166667,0.166667,...,0.0,0,0,100,100,27.5,28.0,27.0,27.5,27.5
3,2018-07-24 18:03:00,1,3.0,0.000000,0.000000,914.000000,25.45,57.0,0.000000,5.500000,...,0.0,0,0,100,100,27.5,28.0,27.0,27.5,27.5
4,2018-07-24 18:04:00,1,3.0,0.000000,0.000000,912.833333,25.45,57.0,0.000000,4.000000,...,0.0,0,0,100,100,27.5,28.0,27.0,27.5,27.5
5,2018-07-24 18:05:00,1,2.0,0.000000,0.000000,911.666667,25.50,57.0,0.000000,0.000000,...,0.0,0,0,100,100,27.5,28.0,27.0,27.5,27.5
6,2018-07-24 18:06:00,1,2.0,0.333333,0.333333,914.000000,25.45,57.0,0.333333,1.666667,...,0.0,0,0,100,100,27.5,28.0,27.0,27.5,27.5
7,2018-07-24 18:07:00,1,3.0,0.000000,0.000000,914.333333,25.45,57.0,0.333333,4.500000,...,0.0,0,0,100,100,27.5,28.0,27.0,27.5,27.5
8,2018-07-24 18:08:00,1,3.0,0.000000,0.000000,914.166667,25.50,57.0,0.500000,0.500000,...,0.0,0,0,100,100,27.5,28.0,27.0,27.5,27.5
9,2018-07-24 18:09:00,1,3.0,0.000000,0.000000,912.500000,25.50,57.0,0.000000,0.000000,...,0.0,0,0,100,100,27.5,28.0,27.0,27.5,27.5
10,2018-07-24 18:10:00,1,3.0,0.500000,0.500000,912.666667,25.50,57.0,0.500000,0.500000,...,0.0,0,0,100,100,27.5,28.0,27.0,27.5,27.5
11,2018-07-24 18:11:00,1,3.0,0.000000,0.166667,912.333333,25.50,57.0,0.000000,0.000000,...,0.0,0,0,100,100,27.5,28.0,27.0,27.5,27.5
12,2018-07-24 18:12:00,1,3.0,0.166667,0.166667,912.166667,25.50,57.0,0.000000,0.000000,...,0.0,0,0,100,100,27.5,28.0,27.0,27.5,27.5
13,2018-07-24 18:13:00,1,3.0,0.000000,0.000000,909.666667,25.45,57.0,0.000000,1.333333,...,0.0,0,0,100,100,27.5,28.0,27.0,27.5,27.0
14,2018-07-24 18:14:00,1,3.0,0.000000,0.000000,909.333333,25.50,57.0,0.000000,0.000000,...,0.0,0,0,100,100,27.5,28.0,27.0,27.5,27.0
15,2018-07-24 18:15:00,1,3.0,0.000000,0.000000,907.833333,25.50,57.0,0.000000,0.000000,...,0.0,0,0,100,100,27.5,28.0,27.0,27.5,27.0
16,2018-07-24 18:16:00,1,3.0,0.000000,0.000000,906.000000,25.50,57.0,0.000000,1.333333,...,0.0,0,0,100,100,27.5,28.0,27.0,27.5,27.0
17,2018-07-24 18:17:00,1,3.0,0.000000,0.000000,906.500000,25.50,57.0,0.000000,0.000000,...,0.0,0,0,100,100,27.5,28.0,27.0,27.5,27.0
18,2018-07-24 18:18:00,1,3.0,0.000000,0.000000,905.666667,25.50,57.0,0.000000,0.000000,...,0.0,0,0,100,100,27.5,28.0,27.0,27.5,27.0
19,2018-07-24 18:19:00,1,2.0,0.000000,0.000000,903.666667,25.50,57.0,0.000000,0.000000,...,0.0,0,0,100,100,27.5,28.0,27.0,27.5,27.0
20,2018-07-24 18:20:00,1,3.0,0.000000,0.000000,903.000000,25.50,57.0,0.000000,0.000000,...,0.0,0,0,100,100,27.5,28.0,27.0,27.5,27.0
21,2018-07-24 18:21:00,1,4.0,0.000000,0.000000,902.833333,25.50,57.0,0.000000,0.000000,...,0.0,0,0,100,100,27.5,28.0,27.0,27.5,27.0
22,2018-07-24 18:22:00,1,2.0,0.000000,0.000000,902.000000,25.50,57.0,0.000000,5.500000,...,0.0,0,0,100,100,27.5,28.0,27.0,27.5,27.0
23,2018-07-24 18:23:00,1,3.0,0.000000,0.000000,902.000000,25.50,57.0,0.000000,0.000000,...,0.0,0,0,100,100,27.5,28.0,27.0,27.5,27.0
24,2018-07-24 18:24:00,1,3.0,0.000000,0.000000,900.666667,25.50,57.0,0.000000,0.000000,...,0.0,0,0,100,100,27.5,28.0,27.0,27.5,27.0
25,2018-07-24 18:25:00,1,3.0,0.000000,0.000000,899.000000,25.50,57.0,0.000000,0.000000,...,0.0,0,0,100,100,27.5,28.0,27.0,27.5,27.0
26,2018-07-24 18:26:00,1,3.0,0.000000,0.000000,897.333333,25.50,57.0,0.000000,0.000000,...,0.0,0,0,100,100,27.0,28.0,27.0,27.5,27.0
27,2018-07-24 18:27:00,1,3.0,0.000000,0.000000,898.333333,25.50,57.0,0.000000,0.000000,...,0.0,0,0,100,100,27.0,28.0,27.0,27.5,27.0
28,2018-07-24 18:28:00,1,3.0,0.000000,0.000000,898.166667,25.50,57.0,0.000000,0.000000,...,0.0,0,0,100,100,27.0,28.0,27.0,27.5,27.0
29,2018-07-24 18:29:00,1,3.0,0.000000,0.000000,897.833333,25.50,57.0,0.000000,0.000000,...,0.0,0,0,100,100,27.0,28.0,27.0,27.5,27.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9511,2018-07-31 08:31:00,2,8.0,0.833333,0.833333,703.500000,22.50,58.0,1.500000,12.666667,...,0.0,0,0,100,100,26.0,30.5,26.0,27.0,28.0
9512,2018-07-31 08:32:00,2,7.0,1.000000,1.000000,704.333333,22.50,58.0,1.666667,8.000000,...,0.0,0,0,100,100,26.0,30.0,26.0,27.0,28.0
9513,2018-07-31 08:33:00,2,7.0,1.000000,1.333333,703.833333,22.50,58.0,1.333333,7.500000,...,0.0,0,0,100,100,26.0,29.5,25.5,26.5,28.0
9514,2018-07-31 08:34:00,2,7.0,0.833333,0.833333,703.000000,22.50,58.0,1.000000,10.833333,...,0.0,0,0,100,100,26.0,29.5,25.5,26.5,27.5
9515,2018-07-31 08:35:00,2,7.0,1.000000,1.000000,701.500000,22.55,58.0,1.000000,1.000000,...,0.0,0,0,100,100,26.0,29.5,25.5,26.5,27.5
9516,2018-07-31 08:36:00,2,8.0,1.000000,1.000000,699.166667,22.55,58.0,1.500000,1.500000,...,0.0,0,0,100,100,25.5,29.0,25.5,26.5,27.5
9517,2018-07-31 08:37:00,2,9.0,0.833333,0.833333,698.500000,22.50,58.0,1.000000,4.500000,...,0.0,0,0,100,100,25.5,29.0,25.5,26.5,27.5
9518,2018-07-31 08:38:00,2,8.0,1.000000,1.166667,698.000000,22.50,58.0,1.333333,6.000000,...,0.0,0,0,100,100,25.5,28.5,25.5,26.0,27.0
9519,2018-07-31 08:39:00,2,9.0,1.000000,1.666667,698.833333,22.60,58.0,1.000000,8.333333,...,0.0,0,0,100,100,25.5,28.0,25.0,26.0,27.0
9520,2018-07-31 08:40:00,2,8.0,1.000000,1.000000,698.000000,22.50,58.0,1.166667,8.333333,...,0.0,0,0,100,100,25.5,28.0,25.0,26.0,27.0
9521,2018-07-31 08:41:00,2,8.0,1.000000,1.000000,698.166667,22.50,58.0,1.000000,12.166667,...,0.0,0,0,100,100,25.5,28.0,25.0,25.5,27.0
9522,2018-07-31 08:42:00,2,9.0,1.000000,1.000000,699.000000,22.50,58.0,1.000000,3.500000,...,0.0,0,0,100,100,25.5,27.5,25.0,25.5,27.0
9523,2018-07-31 08:43:00,2,9.0,1.000000,1.000000,698.333333,22.50,58.0,1.000000,13.333333,...,0.0,0,0,100,100,25.5,27.5,25.0,25.5,27.0
9524,2018-07-31 08:44:00,2,8.0,0.666667,0.666667,697.166667,22.50,58.0,0.666667,6.833333,...,0.0,0,0,100,100,25.5,27.5,25.0,25.5,27.0
9525,2018-07-31 08:45:00,2,9.0,0.833333,0.833333,696.500000,22.50,58.0,1.000000,1.000000,...,0.0,0,0,100,100,25.0,27.5,25.0,25.5,26.5
9526,2018-07-31 08:46:00,2,9.0,1.000000,1.000000,696.666667,22.50,57.0,0.666667,7.833333,...,0.0,0,0,100,100,25.0,27.5,24.5,25.5,26.5
9527,2018-07-31 08:47:00,2,9.0,0.833333,0.833333,697.000000,22.50,58.0,1.000000,5.833333,...,0.0,0,0,100,100,25.0,27.0,24.5,25.5,26.5
9528,2018-07-31 08:48:00,2,8.0,0.833333,1.166667,696.333333,22.50,58.0,1.000000,3.333333,...,0.0,0,0,100,100,25.0,27.0,24.5,25.5,26.5
9529,2018-07-31 08:49:00,2,9.0,1.000000,1.166667,696.000000,22.50,58.0,1.333333,1.333333,...,0.0,0,0,100,100,25.0,27.0,24.5,25.5,26.5
9530,2018-07-31 08:50:00,2,9.0,1.000000,1.000000,695.166667,22.50,57.5,1.000000,8.500000,...,0.0,0,0,100,100,25.0,27.0,24.5,25.0,26.5
9531,2018-07-31 08:51:00,2,9.0,0.666667,0.666667,692.833333,22.50,57.0,1.000000,4.500000,...,0.0,0,0,100,100,25.0,26.5,24.5,25.0,26.0
9532,2018-07-31 08:52:00,2,9.0,1.000000,1.000000,693.333333,22.50,57.5,1.000000,1.000000,...,0.0,0,0,100,100,25.0,26.5,24.5,25.0,26.0
9533,2018-07-31 08:53:00,2,9.0,1.000000,1.000000,695.166667,22.50,57.0,1.166667,1.166667,...,0.0,0,0,100,100,25.0,26.5,24.5,25.0,26.0
9534,2018-07-31 08:54:00,2,9.0,1.000000,1.000000,699.000000,22.50,57.5,1.000000,4.500000,...,0.0,0,0,100,100,24.5,26.5,24.5,25.0,26.0
9535,2018-07-31 08:55:00,2,9.0,1.000000,1.166667,698.833333,22.50,57.5,1.000000,2.166667,...,0.0,0,0,100,100,24.5,26.5,24.5,25.0,26.0
9536,2018-07-31 08:56:00,2,7.0,1.000000,2.333333,705.333333,22.50,57.0,1.000000,7.000000,...,0.0,0,0,100,100,24.5,26.5,24.5,25.0,25.5
9537,2018-07-31 08:57:00,2,7.0,1.000000,1.166667,715.166667,22.50,58.0,0.666667,0.666667,...,0.0,0,0,100,100,24.5,26.5,24.5,25.0,25.5
9538,2018-07-31 08:58:00,3,7.0,1.000000,1.000000,720.500000,22.50,59.0,1.000000,3.333333,...,0.0,0,0,100,100,24.5,26.5,24.5,25.0,25.5
9539,2018-07-31 08:59:00,3,6.0,1.000000,1.500000,720.000000,22.55,59.0,1.000000,2.166667,...,0.0,0,0,100,100,24.5,26.5,24.5,25.0,25.5
9540,2018-07-31 09:00:00,3,6.0,1.000000,1.000000,716.166667,22.60,59.0,1.000000,1.000000,...,0.0,0,100,100,100,24.5,26.5,24.5,25.0,25.5

In [9]:
time = df["Time"].values
pmin = df["PMin"].values
pmout = df["PMout"].values
AVP_BR1_PM25 = df["AVP_BR1_PM25"].values
AVP_BR1_PM10 = df["AVP_BR1_PM10"].values
AVP_BR1_CO2 = df["AVP_BR1_CO2"].values
AVP_BR1_T = df["AVP_BR1_T"].values
AVP_BR1_RH = df["AVP_BR1_RH"].values
AVP_IN1_PM25 = df["AVP_IN1_PM25"].values
AVP_IN1_PM10 = df["AVP_IN1_PM10"].values
AVP_IN1_CO2 = df["AVP_IN1_CO2"].values
AVP_IN1_T = df["AVP_IN1_T"].values
AVP_IN1_RH = df["AVP_IN1_RH"].values
AVP_IN2_PM25 = df["AVP_IN2_PM25"].values
AVP_IN2_PM10 = df["AVP_IN2_PM10"].values
AVP_IN2_T = df["AVP_IN2_T"].values
AVP_IN2_RH = df["AVP_IN2_RH"].values
BR1_T = df["BR1_T"].values
BR1_RH = df["BR1_RH"].values
BS_T = df["BS_T"].values
BS_RH = df["BS_RH"].values
IN1_T = df["IN1_T"].values
IN1_RH = df["IN1_RH"].values
OUT_T = df["OUT_T"].values
OUT_RH = df["OUT_RH"].values
OUT2_T = df["OUT2_T"].values
OUT2_RH = df["OUT2_RH"].values
ANM_AS10 = df["ANM_AS10"].values
ANM_BA3 = df["ANM_BA3"].values
ANM_CDR = df["ANM_CDR"].values
ANM_EF1 = df["ANM_EF1"].values
ANM_RHD = df["ANM_RHD"].values
MTR_CDR = df["MTR_CDR"].values
STA_BR1 = df["STA_BR1"].values
STA_DFR = df["STA_DFR"].values
STA_DP1 = df["STA_DP1"].values
IBU_CLB = df["IBU_CLB"].values
IBU_CLF = df["IBU_CLF"].values
IBU_CRB = df["IBU_CRB"].values
IBU_CRF = df["IBU_CRF"].values
IBU_OVN = df["IBU_OVN"].values

In [41]:
x = "AVP_BR1_CO2"
print("<p>"+"<b>"+x+"<br>"+"</b>")
print("Mean: "+str(df.loc[:,x].mean()) + "<br>")
print("Minimum: "+str(df.loc[:,x].min()) + "<br>")
print("5th Percentile: "+str(df.loc[:,x].quantile(q=0.05)) + "<br>")
print("25th Percentile: "+str(df.loc[:,x].quantile(q=0.25)) + "<br>")
print("Median: "+str(df.loc[:,x].median()) + "<br>")
print("75th Percentile: "+str(df.loc[:,x].quantile(q=0.75)) + "<br>")
print("95th Percentile: "+str(df.loc[:,x].quantile(q=0.95)) + "<br>")
print("Maximum: "+str(df.loc[:,x].max())+"<br></p>")

<p><b>AVP_BR1_PM10<br></b>
Mean: 0.40226391363588715<br>
Minimum: 0.0<br>
5th Percentile: 0.0<br>
25th Percentile: 0.0<br>
Median: 0.0<br>
75th Percentile: 0.0<br>
95th Percentile: 2.0<br>
Maximum: 159.0<br></p>

In [22]:
output_file("pm.html")
plo = figure(title="PMin & PMOut", x_axis_label='Time', y_axis_label='ug/m3', x_axis_type='datetime')
plo.line(time, pmin, legend="PMin", line_width=2, color ='red')
plo.line(time, pmout, legend="PMout.", line_width=2, color ='blue')
show(plo)

In [23]:
output_file("pm10.html")
plo = figure(title="PM10", x_axis_label='Time', y_axis_label='ug/m3', x_axis_type='datetime')
plo.line(time, AVP_BR1_PM10, legend="AVP_BR1_PM10", line_width=2, color ='red')
plo.line(time, AVP_IN1_PM10, legend="AVP_IN1_PM10.", line_width=2, color ='blue')
plo.line(time, AVP_IN2_PM10, legend="AVP_IN2_PM10.", line_width=2, color ='green')
show(plo)

In [24]:
output_file("intemp.html")
plo = figure(title="Indoor Temperature", x_axis_label='Time', y_axis_label='oC', x_axis_type='datetime')
plo.line(time, AVP_BR1_T, legend="AVP_BR1_T", line_width=2, color ='red')
plo.line(time, AVP_IN1_T, legend="AVP_IN1_T.", line_width=2, color ='blue')
plo.line(time, AVP_IN2_T, legend="AVP_IN2_T.", line_width=2, color ='green')
plo.line(time, BR1_T, legend="BR1_T", line_width=2, color ='purple')
plo.line(time, BS_T, legend="BS_T.", line_width=2, color ='orange')
plo.line(time, IN1_T, legend="IN1_T.", line_width=2, color ='yellow')
show(plo)

In [25]:
output_file("pm25.html")
plo = figure(title="PM25", x_axis_label='Time', y_axis_label='ug/m3', x_axis_type='datetime')
plo.line(time, AVP_BR1_PM25, legend="AVP_BR1_PM25", line_width=2, color ='red')
plo.line(time, AVP_IN1_PM25, legend="AVP_IN1_PM25.", line_width=2, color ='blue')
plo.line(time, AVP_IN2_PM25, legend="AVP_IN2_PM25", line_width=2, color ='green')
show(plo)

In [26]:
output_file("outtemp.html")
plo = figure(title="Outdoor Temperature", x_axis_label='Time', y_axis_label='oC', x_axis_type='datetime')
plo.line(time, OUT_T, legend="OUT_T", line_width=2, color ='red')
plo.line(time, OUT2_T, legend="OUT2_T", line_width=2, color ='blue')
show(plo)

In [27]:
output_file("ibo.html")
plo = figure(title="iButtons", x_axis_label='Time', y_axis_label='oC', x_axis_type='datetime')
plo.line(time, IBU_CLB, legend="IBU_CLB", line_width=2, color ='red')
plo.line(time, IBU_CLF, legend="IBU_CLF", line_width=2, color ='blue')
plo.line(time, IBU_CRB, legend="IBU_CRB", line_width=2, color ='green')
plo.line(time, IBU_CRF, legend="IBU_CRF", line_width=2, color ='purple')
plo.line(time, IBU_OVN, legend="IBU_OVN", line_width=2, color ='orange')
show(plo)

In [28]:
output_file("inrh.html")
plo = figure(title="Indoor Relative Humidity", x_axis_label='Time', y_axis_label='%', x_axis_type='datetime')
plo.line(time, AVP_BR1_RH, legend="AVP_BR1_RH", line_width=2, color ='red')
plo.line(time, AVP_IN1_RH, legend="AVP_IN1_RH", line_width=2, color ='blue')
plo.line(time, AVP_IN2_RH, legend="AVP_IN2_RH", line_width=2, color ='green')
plo.line(time, BR1_RH, legend="BR1_RH", line_width=2, color ='purple')
plo.line(time, BS_RH, legend="BS_RH", line_width=2, color ='orange')
plo.line(time, IN1_RH, legend="IN1_RH", line_width=2, color ='yellow')
show(plo)

In [29]:
output_file("outrh.html")
plo = figure(title="Outdoor Relative Humidity", x_axis_label='Time', y_axis_label='%', x_axis_type='datetime')
plo.line(time, OUT_T, legend="OUT_RH", line_width=2, color ='red')
plo.line(time, OUT2_T, legend="OUT2_RH", line_width=2, color ='blue')
show(plo)

In [30]:
output_file("co2.html")
plo = figure(title="CO2", x_axis_label='Time', y_axis_label='ppm', x_axis_type='datetime')
plo.line(time, AVP_BR1_CO2, legend="AVP_BR1_CO2", line_width=2, color ='red')
plo.line(time, AVP_IN1_CO2, legend="AVP_IN1_CO2", line_width=2, color ='blue')
show(plo)

In [31]:
output_file("anm.html")
plo = figure(title="Anomometer", x_axis_label='Time', y_axis_label='m/s', x_axis_type='datetime')
plo.line(time, ANM_AS10, legend="ANM_AS10", line_width=2, color ='red')
plo.line(time, ANM_BA3, legend="ANM_BA3", line_width=2, color ='blue')
plo.line(time, ANM_CDR, legend="ANM_CDR", line_width=2, color ='green')
plo.line(time, ANM_EF1, legend="ANM_EF1", line_width=2, color ='purple')
plo.line(time, ANM_RHD, legend="ANM_RHD", line_width=2, color ='orange')
show(plo)

In [32]:
output_file("mtr.html")
plo = figure(title="Motor", x_axis_label='Time', y_axis_label='% time on', x_axis_type='datetime')
plo.line(time, MTR_CDR, legend="MTR_CDR", line_width=2, color ='red')
show(plo)

In [33]:
output_file("sta.html")
plo = figure(title="Door Status", x_axis_label='Time', y_axis_label='Status', x_axis_type='datetime')
plo.line(time, STA_BR1, legend="STA_BR1", line_width=2, color ='red')
plo.line(time, STA_DFR, legend="STA_DFR", line_width=2, color ='blue')
plo.line(time, STA_DP1, legend="STA_DP1", line_width=2, color ='green')
show(plo)